### ISSUE TITLE
feat: add support for `user.signingKey`

### ISSUE THREAD

**Issue by ayakovlenko** [ayakovlenko/zit#32]
```yaml
users:
  work: &work_user
    name: "John Doe"
    email: "john.doe@corp.com"
    sign:
      key: "<path to ssh key>"
      format: "ssh"

hosts:
  "github.com":
    overrides:
      - owner: "corp"
        user: *work_user
```

Set:

```
git config --local commit.gpgsign true

git config --local user.signingKey "<path to ssh key>"

git config --local  gpg.format ssh
```
